travis:
  secure:
    BINSTAR_TOKEN: BksO74bbIy2OVKEXtGWynRXCXraXuk9nx0+ODVgj/QxJ5X8OhHQmpM7u8dpFEJCpSRKUVz5QvGnS+OyA++bOO3dh/LrpdGZeJlfIdmrpdpcTdgtJxELnOrfj6gzDIlnQU+BUmWiF/u/TS8igw+U1HnRPzjI8KqZmABlNtj2JBkpDlbjiDi7t2HWGQafSaLAe98kiiAmG4Y6BOuHSGKDlbJF4fcMHIi7pyLsxRyM7eTRCi5LZImPsNaWlzP2qQzdJ5abamdp4AqE9J44ap4BE9v3BmRvz1mi9cEK3zxi1crqj0YjbdOA0W/k63IqxMr0XAxQnYMflROsvHXxV0YTPMkSFcGDik7JJkN/Dj55zODxteZROOyTMMm+7eMtLND295x4LBnBwC/n80Nb52DGxXnworWwPeLu+chG/sBFuBdMVxx9aPAyXqDF45FLbWhyLmYqjc1Y+RrHhqOgghKOY9k2Hr5793D4QR2hPzLgGpm9blQWy+DPVMhkN0kKI6GK1KX2v+x6+1nsP21zaz9stlCFnS69rjCb1FWExdDDpHoXAmtDyNguQb5wjsK7i0IB7m/KiE29EFn2/9f258TFao7hgRJOeUam9mXW4teEjdQ3J0ls6RPJZLVaQJtYZ5EH/J3CXOJ2hG3vgm3CroBE+tgUepjh4DyicggzN0MJYAOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
